# Generated by Django 6.0.5 on 2026-06-02 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Booth')),
                ('location', models.CharField(max_length=300, verbose_name='Lokasi')),
                ('booth_type', models.CharField(choices=[('minuman', 'Minuman'), ('makanan', 'Makanan'), ('campuran', 'Campuran')], max_length=20, verbose_name='Tipe')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Nonaktif')], default='active', max_length=20)),
                ('icon', models.CharField(choices=[('fa-mug-hot', 'Kopi/Minuman'), ('fa-drumstick-bite', 'Ayam/Makanan'), ('fa-blender', 'Smoothie'), ('fa-glass-water', 'Es Teh'), ('fa-ice-cream', 'Dessert'), ('fa-utensils', 'Restoran')], default='fa-mug-hot', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booth',
                'verbose_name_plural': 'Booth',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('position', models.CharField(max_length=100, verbose_name='Posisi')),
                ('shift', models.CharField(choices=[('pagi', 'Pagi (06:00 - 14:00)'), ('siang', 'Siang (14:00 - 22:00)'), ('malam', 'Malam (22:00 - 06:00)')], max_length=20)),
                ('phone', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Nonaktif')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='boothapp.booth')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Bahan')),
                ('category', models.CharField(choices=[('bahan_minuman', 'Bahan Minuman'), ('bahan_makanan', 'Bahan Makanan'), ('kemasan', 'Kemasan')], max_length=30, verbose_name='Kategori')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('unit', models.CharField(max_length=30, verbose_name='Satuan')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Stok Minimum')),
                ('price_per_unit', models.PositiveIntegerField(default=0, verbose_name='Harga per Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='boothapp.booth')),
            ],
            options={
                'verbose_name': 'Bahan Baku',
                'verbose_name_plural': 'Bahan Baku',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Menu')),
                ('price', models.PositiveIntegerField(verbose_name='Harga')),
                ('category', models.CharField(choices=[('minuman', 'Minuman'), ('makanan', 'Makanan')], max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='boothapp.booth')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('payment', models.CharField(choices=[('tunai', 'Tunai'), ('digital', 'Digital (QRIS/Transfer)')], max_length=20, verbose_name='Metode Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='boothapp.booth')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('price', models.PositiveIntegerField(verbose_name='Harga Satuan')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boothapp.menuitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boothapp.sale')),
            ],
        ),
    ]
