# Generated by Django 6.0.5 on 2026-06-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boothapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('karyawan', 'Biaya Karyawan'), ('sewa', 'Sewa Tempat'), ('investasi', 'Investasi Awal'), ('operasional', 'Operasional Harian')], max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(max_length=200, verbose_name='Deskripsi')),
                ('amount', models.PositiveIntegerField(verbose_name='Jumlah Biaya')),
                ('date', models.DateField(verbose_name='Tanggal Pengeluaran')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Biaya Berulang (Bulanan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='boothapp.booth')),
            ],
            options={
                'verbose_name': 'Biaya Operasional',
                'verbose_name_plural': 'Biaya Operasional',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
